### PR TITLE
AO-12: Update documentation to point to Add Ons instead of Modulus

### PR DESCRIPTION
**Pull request by f4ww4z**
https://issues.openmrs.org/browse/AO-12

I found https://modules.openmrs.org links which should be updated to https://addons.openmrs.org/ .

### CODE REVIEW

**Comment by dkayiwa** [comment]
@f4ww4z are you still working on this? If yes, did you take a look at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by f4ww4z** [comment]
@dkayiwa I have finished work on this ticket.

**Comment by dkayiwa** [comment]
@f4ww4z the JIRA ticket shows that you are still doing more work on this. https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by f4ww4z** [comment]
Oops, sorry for the late update on JIRA @dkayiwa !

**Pull request merged**
